version: '3'
    
services:
    nginx:
        image: nginx:1.16.1
        restart: always
        volumes:
           - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        environment:
            NGINX_PORT: "80"
        ports:
            - "8000:80"
        depends_on:
            - web

    db:
        image: mongo:3.6.17
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: examplepassword
            MONGO_INITDB_DATABASE: exampledb
        volumes:
            - ./db-data:/data/db
            - ./db-init:/docker-entrypoint-initdb.d
        expose:
            - 27017
    
    web:
        image: app
        command: uwsgi --socket :8000 --module capstone.wsgi
        volumes:
            - ./app:/app
        expose:
            - 8000
        depends_on:
            - migrate
    
    migrate:
        build: 
            context: ./app
        image: app
        command: python manage.py migrate
        volumes:
            - ./app:/app
        depends_on:
            - make_migrations

    make_migrations:
        build: ./app
        image: app
        command: python manage.py makemigrations
        volumes:
            - ./app:/app
        depends_on:
            - db