#!/usr/bin/env bash

# Export UID and GID for use in docker-compose.
export USER_ID=$(id -u)
export GROUP_ID=$(id -g)

# Create directories that will be mounted as volume in containers.
# docker-compose will create them if we don't, but then they will be owned by
# root:root, which isn't what we want.
mkdir -p \
    file/partial \
    file/complete \
    file/thumbnail \
    db/data \
    log \
    nginx/certbot/conf \
    nginx/certbot/www

# Delegate to docker-compose.
exec docker-compose "$@"