# Generated by Django 2.2.12 on 2020-06-03 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_account', '0004_auto_20200601_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_mail_authenticated',
            field=models.BooleanField(default=False),
        ),
    ]
