# Generated by Django 2.2.12 on 2020-06-03 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_account', '0006_auto_20200603_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
