# Generated by Django 2.2.12 on 2020-05-23 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('teamName', models.CharField(max_length=20)),
                ('invitationList', models.ManyToManyField(blank=True, related_name='invitationList', to=settings.AUTH_USER_MODEL)),
                ('memberList', models.ManyToManyField(blank=True, related_name='memberList', to=settings.AUTH_USER_MODEL)),
                ('shareFolders', models.ManyToManyField(blank=True, to='storage.Directory')),
                ('teamLeader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leader', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
