# Generated by Django 2.2.12 on 2020-05-17 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone.thumbnail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.URLField(max_length=300),
        ),
    ]
