# Generated by Django 2.2.12 on 2020-05-18 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone.thumbnail', '0003_auto_20200517_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.URLField(max_length=300),
        ),
    ]
