# Generated by Django 2.2.12 on 2020-05-18 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone.thumbnail', '0004_auto_20200518_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
