# Generated by Django 2.2.12 on 2020-05-18 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone.thumbnail', '0005_auto_20200518_1308'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
