# Generated by Django 3.0.6 on 2020-05-29 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('capstone_account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectoryEntry',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('directoryentry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='storage.DirectoryEntry')),
            ],
            bases=('storage.directoryentry',),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('directoryentry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='storage.DirectoryEntry')),
                ('size', models.BigIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('has_thumbnail', models.BooleanField(default=False)),
            ],
            bases=('storage.directoryentry',),
        ),
        migrations.CreateModel(
            name='PartialUpload',
            fields=[
                ('directoryentry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='storage.DirectoryEntry')),
                ('size', models.BigIntegerField()),
                ('received_bytes', models.BigIntegerField(default=0)),
                ('last_receive_time', models.DateTimeField(auto_now=True)),
            ],
            bases=('storage.directoryentry',),
        ),
        migrations.CreateModel(
            name='UserStorage',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='root_info', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('capacity', models.BigIntegerField(default=5368709120)),
                ('file_count', models.BigIntegerField(default=0)),
                ('dir_count', models.BigIntegerField(default=0)),
                ('file_size_total', models.BigIntegerField(default=0)),
                ('root_dir', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='storage.Directory')),
            ],
        ),
        migrations.AddField(
            model_name='directoryentry',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='storage.Directory'),
        ),
        migrations.AddConstraint(
            model_name='directoryentry',
            constraint=models.UniqueConstraint(condition=models.Q(parent__isnull=False), fields=('parent', 'name'), name='unique_name_within_directory'),
        ),
    ]
