# Generated by Django 2.2.12 on 2020-05-23 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('capstone_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_dirs', to='storage.Directory')),
            ],
        ),
        migrations.CreateModel(
            name='UserStorage',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('capacity', models.BigIntegerField(default=5368709120)),
                ('file_count', models.BigIntegerField(default=0)),
                ('dir_count', models.BigIntegerField(default=0)),
                ('file_size_total', models.BigIntegerField(default=0)),
                ('root_dir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.Directory')),
            ],
        ),
        migrations.CreateModel(
            name='PartialUpload',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('file_size', models.BigIntegerField()),
                ('received_bytes', models.BigIntegerField(default=0)),
                ('last_receive_time', models.DateTimeField(auto_now_add=True)),
                ('file_name', models.CharField(default='', max_length=256)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('size', models.BigIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('directory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='storage.Directory')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='file',
            constraint=models.UniqueConstraint(fields=('directory', 'name'), name='unique_file_name'),
        ),
        migrations.AddConstraint(
            model_name='directory',
            constraint=models.UniqueConstraint(condition=models.Q(parent__isnull=False), fields=('parent', 'name'), name='unique_directory_name'),
        ),
    ]
