# Generated by Django 2.2.12 on 2020-06-04 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='is_video',
            field=models.BooleanField(default=False),
        ),
    ]
