# Generated by Django 3.0.6 on 2020-05-25 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directoryentry',
            name='kind',
        ),
    ]
