# Generated by Django 2.2.12 on 2020-05-22 07:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partialupload',
            name='id',
        ),
        migrations.AddField(
            model_name='partialupload',
            name='_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
