# Generated by Django 3.0.6 on 2020-06-05 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storage', '0002_file_is_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='directoryentry',
            name='favorite_of',
            field=models.ManyToManyField(related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='directoryentry',
            name='in_recycle',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='RecycleEntry',
            fields=[
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='+', serialize=False, to='storage.DirectoryEntry')),
                ('former_parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='storage.Directory')),
            ],
        ),
    ]
