# Generated by Django 2.2.12 on 2020-05-23 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_auto_20200523_1118'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='file',
            name='unique_file_name',
        ),
        migrations.AddField(
            model_name='file',
            name='is_thumbnail',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='file',
            constraint=models.UniqueConstraint(fields=('directory', 'name'), name='unique_ ile_name'),
        ),
    ]
