# Generated by Django 2.2.12 on 2020-05-23 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_auto_20200523_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstorage',
            name='root_dir',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userdir_info', to='storage.Directory'),
        ),
    ]
