# Generated by Django 3.0.6 on 2020-05-24 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_auto_20200523_1550'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='file',
            name='unique_ ile_name',
        ),
        migrations.AlterField(
            model_name='userstorage',
            name='root_dir',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.Directory'),
        ),
        migrations.AddConstraint(
            model_name='file',
            constraint=models.UniqueConstraint(fields=('directory', 'name'), name='unique_file_name'),
        ),
    ]
