# Generated by Django 3.0.6 on 2020-05-24 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_auto_20200523_1550'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='file',
            name='unique_ ile_name',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='is_thumbnail',
            new_name='has_thumbnail',
        ),
        migrations.AlterField(
            model_name='partialupload',
            name='last_receive_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userstorage',
            name='root_dir',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='storage.Directory'),
        ),
        migrations.AddConstraint(
            model_name='file',
            constraint=models.UniqueConstraint(fields=('directory', 'name'), name='unique_file_name'),
        ),
    ]
