# Generated by Django 3.0.6 on 2020-05-25 03:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storage', '0005_auto_20200524_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectoryEntry',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('kind', models.CharField(choices=[('D', 'Directory'), ('F', 'File'), ('P', 'Partial upload')], max_length=1)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='directory',
            name='unique_directory_name',
        ),
        migrations.RemoveConstraint(
            model_name='file',
            name='unique_file_name',
        ),
        migrations.RenameField(
            model_name='partialupload',
            old_name='file_size',
            new_name='size',
        ),
        migrations.RemoveField(
            model_name='directory',
            name='_id',
        ),
        migrations.RemoveField(
            model_name='directory',
            name='name',
        ),
        migrations.RemoveField(
            model_name='directory',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='directory',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='file',
            name='_id',
        ),
        migrations.RemoveField(
            model_name='file',
            name='directory',
        ),
        migrations.RemoveField(
            model_name='file',
            name='name',
        ),
        migrations.RemoveField(
            model_name='file',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='partialupload',
            name='_id',
        ),
        migrations.RemoveField(
            model_name='partialupload',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='partialupload',
            name='uploader',
        ),
        migrations.AddConstraint(
            model_name='directory',
            constraint=models.UniqueConstraint(condition=models.Q(parent__isnull=True), fields=('owner',), name='one_root_per_user'),
        ),
        migrations.AddConstraint(
            model_name='directory',
            constraint=models.CheckConstraint(check=models.Q(kind='D'), name='matching_kind_directory'),
        ),
        migrations.AddConstraint(
            model_name='file',
            constraint=models.CheckConstraint(check=models.Q(parent__isnull=False), name='file_has_parent_directory'),
        ),
        migrations.AddConstraint(
            model_name='file',
            constraint=models.CheckConstraint(check=models.Q(kind='F'), name='matching_kind_file'),
        ),
        migrations.AddConstraint(
            model_name='partialupload',
            constraint=models.CheckConstraint(check=models.Q(parent__isnull=False), name='partial_upload_has_parent_directory'),
        ),
        migrations.AddConstraint(
            model_name='partialupload',
            constraint=models.CheckConstraint(check=models.Q(kind='P'), name='matching_kind_partial_upload'),
        ),
        migrations.AddField(
            model_name='directoryentry',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='directoryentry',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='storage.Directory'),
        ),
        migrations.AddField(
            model_name='directory',
            name='directoryentry_ptr',
            field=models.OneToOneField(auto_created=True, default='226ed7a5-fe69-40d8-915a-cdd29f69fc1d', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='storage.DirectoryEntry'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='directoryentry_ptr',
            field=models.OneToOneField(auto_created=True, default='226ed7a5-fe69-40d8-915a-cdd29f69fc1d', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='storage.DirectoryEntry'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partialupload',
            name='directoryentry_ptr',
            field=models.OneToOneField(auto_created=True, default='226ed7a5-fe69-40d8-915a-cdd29f69fc1d', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='storage.DirectoryEntry'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='directoryentry',
            constraint=models.UniqueConstraint(condition=models.Q(parent__isnull=False), fields=('parent', 'name'), name='unique_name_within_directory'),
        ),
    ]
