# Generated by Django 3.0.5 on 2020-04-19 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_auto_20200416_2350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password_val',
        ),
    ]
