# Generated by Django 3.0.5 on 2020-04-20 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0006_auto_20200420_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='provider',
            new_name='social_auth',
        ),
    ]
