# Generated by Django 3.0.5 on 2020-04-20 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0008_auto_20200420_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_num',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='전화 번호(선택)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='social_auth',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
