# Generated by Django 2.2.12 on 2020-04-22 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0009_auto_20200421_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_mail_authenticated',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='social_auth',
            field=models.CharField(blank=True, default='None', max_length=20),
        ),
    ]
